### ISSUE TITLE
Add virtual pageview tracking to login-ux so we know which screens people are seeing

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-login-ux#166]
WRT: https://github.com/MozillaFoundation/plan/issues/53#issuecomment-72487509

#### What / Why?
Because the login-ux is displayed as a modal on top of other pages, we don't pick up any pageview level data in Google Analytics about which login-ux screens users are seeing or in which order.

Implementing 'virtual' pageview tracking on these modal windows will allow us to understand where users drop out of the current flow. For example, do people enter their email, but drop out on the `choose your username` page?

#### How:

To add virtual page view tracking, we should use our [webmaker-analytics](http://github.com/mozilla/webmaker-analytics) bower module.

I don't fully understand the workings of login-ux, so I'm not sure how best to include/require this module? I think this is best decided by a dev who understands login-ux better than me.

Once webmaker-analytics is available, we need to fire javascript events on the display of each modal. In particular we want to fire the following [`analytics.virtualPageview()`](https://github.com/mozilla/webmaker-analytics#virtualpageviewvirtualpagepath) events:
- [ ] `analytics.virtualPageview('login-ux/create-a-webmaker-account/email');`
- [ ] `analytics.virtualPageview('login-ux/create-a-webmaker-account/username');`
- [ ] `analytics.virtualPageview('login-ux/welcome-to-webmaker');`
- [ ] `analytics.virtualPageview('login-ux/sign-in-to-webmaker/enter-email');`
- [ ] `analytics.virtualPageview('login-ux/sign-in-to-webmaker/check-your-email');`
- [ ] `analytics.virtualPageview('login-ux/sign-in-to-webmaker/enter-password');`
- [ ] `analytics.virtualPageview('login-ux/reset-password');`

**Comment by adamlofting** [comment]
@secretrobotron: assigning this to you, so that you can assign to the right person :bowtie:

**Comment by secretrobotron** [comment]
@adamlofting ok to consider this as a part of login revision planning? Don't have a definite timeline, but will commence after MWC work settles down at least. This task feels like it's in the low-difficulty/low-risk category for login upgrades (of which there are a handful).

I'm going to rely on the expertise of @cadecairos here. 

:kimono: :vhs: :melon: :meat_on_bone:

**Comment by adamlofting** [comment]
Priority/timing-wise, it's a call for @thisandagain / @simonwex 

But collecting some data up front might help when it comes to the planning.

**Comment by adamlofting** [comment]
To note on this issue. We may redesign this flow before we instrument and start collecting this data. 

If we do, the principles detailed here still apply, but the exact page-views to track will need to be updated to match any changes to the UX.

**Comment by thisandagain** [comment]
Excellent. I'll track this as part of the SOW for the next login sprint. Thanks for the reminder @adamlofting

**Comment by adamlofting** [comment]
To note: this spec may no longer apply depending on how different the codebase for the new login system is.

**Comment by adamlofting** [comment]
id.webmaker.org supersedes this.
